name: Deploy to AWS Lambda
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch_depth: 2

      - name: Set up aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Prepare python
        uses: actions/setup-python@v3

      - name: Build Lambda function
        working-directory: ./mane041-image-generation/
        run: |
          sam build -t template.yaml

      - name: Deploy to AWS
        working-directory: ./mane041-image-generation/
        run: |
          sam deploy --config-file samconfig.toml